# Generated by Django 5.2 on 2025-04-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
