# Generated by Django 5.2 on 2025-04-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_users_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
