# Generated by Django 5.2 on 2025-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, verbose_name='name')),
                ('model', models.CharField(max_length=122, verbose_name='model')),
                ('price', models.CharField(max_length=122, verbose_name='price')),
                ('avg_rating', models.CharField(max_length=122, verbose_name='avg_rating')),
                ('processor_brand', models.CharField(max_length=122, verbose_name='processor_brand')),
                ('num_cores', models.CharField(max_length=122, verbose_name='num_cores')),
                ('processor_speed', models.CharField(max_length=122, verbose_name='processor_speed')),
                ('battery_capacity', models.CharField(max_length=122, verbose_name='battery_capacity')),
                ('fast_charging_available', models.CharField(max_length=122, verbose_name='fast_charging_available')),
                ('ram', models.CharField(max_length=122, verbose_name='ram')),
                ('storage', models.CharField(max_length=122, verbose_name='storage')),
                ('os', models.CharField(max_length=122, verbose_name='os')),
            ],
        ),
    ]
