# Generated by Django 5.2 on 2025-04-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('model', models.CharField(max_length=122)),
                ('price', models.IntegerField()),
                ('avg_rating', models.FloatField()),
                ('processor_brand', models.CharField(max_length=122)),
                ('num_cores', models.IntegerField()),
                ('processor_speed', models.FloatField()),
                ('battery_capacity', models.IntegerField()),
                ('fast_charging_available', models.BooleanField()),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('os', models.CharField(max_length=122)),
            ],
        ),
        migrations.RemoveField(
            model_name='phone',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='fast_charging_available',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='model',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='num_cores',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='os',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='price',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='processor_brand',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='processor_speed',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='storage',
        ),
    ]
